# Generated by Django 3.2.9 on 2022-01-15 15:54

import datetime
from django.db import migrations, models
import sketchapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=sketchapp.models.file_upload)),
                ('banner', models.FileField(blank=True, upload_to=sketchapp.models.file_upload)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
