# Generated by Django 3.2.9 on 2022-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
